// Pictionary / Charades word bank, grouped by difficulty tier.
// Used by: pictionary.html (when "My word lists" is selected as the word source)
//
// To add words: find the right tier below (easy / medium / hard) and add
// 'Your New Word' to that array. No other file needs to change.
// - easy/medium: everyday objects, people, places, actions
// - hard: idioms, turns of phrase, and intangible ideas (not obscure trivia)
// Avoid exact duplicates within the same tier; duplicates across tiers are fine.

  window.PICTIONARY_WORDS = {
    easy: [
      'Apple','Car','Chair','Table','Pencil','Eraser','Clock','Phone','Camera','Glasses','Toothbrush','Soap','Towel','Backpack','Scissors','Ruler','Key','Door','Window','Mailbox','Bicycle','Train',
      'Bus','Airplane','Truck','Tractor','Helicopter','Parachute','Motorcycle','Taxi','Pizza','Hamburger','Hot Dog','Sandwich','Donut','Cookie','Popcorn','Watermelon','Strawberry','Pineapple',
      'Orange','Lemon','Carrot','Corn','Mushroom','Broccoli','Cupcake','Pancake','Pretzel','Candy','Lion','Tiger','Bear','Monkey','Giraffe','Zebra','Penguin','Dolphin','Whale','Shark','Turtle','Frog',
      'Snake','Rabbit','Mouse','Horse','Cow','Pig','Chicken','Duck','Butterfly','Ladybug','Spider','Ant','Snail','Bee','Parrot','Owl','Bat','Deer','Sunflower','Rose','Leaf','Acorn','Pinecone',
      'Snowflake','Raindrop','Puddle','Mountain','Island','Beach','River','Lake','Garden','Fence','Bridge','Cave','Crown','Sword','Shield','Wand','Gift','Treasure Chest','Flag','Bell','Drum','Piano',
      'Trumpet','Microphone','Yo-Yo','Puzzle','Dice','Teddy Bear','Flashlight','Candle','Lantern','Magnet','Battery','Light Bulb','Snow Globe','Sun','Tree','Fish','House','Star','Ball','Cat','Dog',
      'Cup','Book','Cloud','Moon','Boat','Egg','Hat','Shoe','Cake','Kite','Fire','Snowman','Umbrella','Ice Cream','Banana','Guitar','Balloon','Toothpaste','Fork','Spoon','Plate','Bowl','Knife',
      'Napkin','Straw','Teapot','Kettle','Frying Pan','Spatula','Oven','Refrigerator','Freezer','Blender','Toaster','Sink','Bathtub','Pillow','Blanket','Mattress','Lamp','Mirror','Curtain','Carpet',
      'Couch','Television','Remote Control','Fan','Socks','Pants','Shirt','Jacket','Gloves','Scarf','Boots','Belt','Tie','Pajamas','Ring','Necklace','Bracelet','Earrings','Watch','Wallet','Purse',
      'Suitcase','Umbrella Hat','Rain Boots','Bus Stop','Gas Station','Parking Lot','Crosswalk','Traffic Light','Stop Sign','Road Cone','Fire Hydrant','Street Lamp','Bench','Skate Park','Playground',
      'Sandbox','Seesaw','Merry-Go-Round','Swing Set','Swimming Pool','Diving Board','Beach Ball','Sandals','Volleyball','Frisbee','Hula Hoop','Soccer Goal','Ping Pong Paddle','Chess Piece',
      'Playing Card','Marbles','Dominoes','Jigsaw Piece','Gift Box','Wrapping Paper','Party Hat','Confetti','Birthday Candle','Invitation','Newspaper','Envelope','Stamp','Alarm Clock','Calculator',
      'Notebook','Crayon','Paintbrush','Paint Palette','Glue','Tape','Stapler','Paperclip','Computer Mouse','Keyboard','Headphones','Charger','Remote','Video Game Controller','Smartwatch','Tablet',
      'Printer','USB Drive','Camera Tripod','Binoculars','Map','Magnifying Glass','Rope','Ladder','Hammer','Screwdriver','Wrench','Axe','Anchor','Arrow','Antenna','Apron','Backhoe','Broom','Bucket',
      'Cage','Calendar','Canoe','Canteen','Comb','Compass','Cork','Crutch','Drill','Dustpan','Eyeglasses Case','Feather','Flagpole','Flowerpot','Funnel','Globe','Hanger','Harmonica','Helmet',
      'Hourglass','Iron','Jar','Juice Box','Ketchup Bottle','Ladle','Lunchbox','Mop','Mug','Oar','Paint Roller','Pail','Pan','Peeler','Pitcher','Plunger','Pocketknife','Rake','Rolling Pin','Sail',
      'Sewing Needle','Shovel','Skillet','Sponge','Spray Bottle','Thermometer','Tissue Box','Toilet Paper','Toolbox','Trash Can','Vacuum Cleaner','Whistle','Wheelbarrow','Zipper','Bookcase',
      'Bookshelf','Desk','Drawer','Dresser','Doorbell','Doormat','Stool','Tablecloth','Vase','Cushion','Hammock','Rocking Chair','Shower','Toilet','Tissue','Towel Rack','Coat Rack','Picture Frame',
      'Wall Clock','Ceiling Fan','Light Switch','Electrical Outlet','Keyhole','Mailbox Flag','Houseplant','Flower','Cactus','Grass','Bush','Branch','Twig','Root','Seed','Acorn Cap','Apple Core',
      'Banana Peel','Coconut','Cherry','Grapes','Blueberry','Raspberry','Peach','Pear','Plum','Kiwi','Mango','Papaya','Avocado','Tomato','Potato','Onion','Garlic','Peas','Bean','Lettuce','Spinach',
      'Cucumber','Pepper','Pumpkin','Radish','Celery','Eggplant','Bread','Toast','Bagel','Muffin','Waffle','Pasta','Noodles','Rice','Cheese','Butter','Bacon','Sausage','Soup','Salad','Taco','Burrito',
      'Nachos','French Fries','Chicken Nugget','Hot Chocolate','Milk','Juice','Lemonade','Water Bottle','Cookie Jar','Gumball','Lollipop','Chocolate Bar','Popsicle','Cotton Candy','Pie','Brownie',
      'Donut Box','Puppy','Kitten','Hamster','Guinea Pig','Goldfish','Lizard','Crocodile','Alligator','Elephant','Hippo','Rhino','Gorilla','Koala','Panda','Sloth','Camel','Goat','Sheep','Donkey',
      'Rooster','Turkey','Peacock','Flamingo','Swan','Seagull','Pelican','Woodpecker','Eagle','Hummingbird','Dove','Crow','Penguin Chick','Jellyfish','Crab','Lobster','Starfish','Seahorse','Clam',
      'Oyster','Squid','Shrimp','Sea Turtle','Whale Tail','Dolphin Fin','Snail Shell','Caterpillar','Grasshopper','Dragonfly','Mosquito','Fly','Worm','Cocoon','Ant Hill','Spider Web','Beehive',
      'Squirrel','Chipmunk','Raccoon','Skunk','Fox','Wolf','Moose','Deer Antlers','Sunrise','Sunset','Rainbow','Lightning','Wind','Fog','Ice Cube','Icicle','Snowball','Cloudburst','Starry Sky',
      'Full Moon','Crescent Moon','Comet','Planet','Rocket Ship','Shooting Star','Pond','Stream','Waterfall','Ocean Wave','Seashell','Sand Dune','Palm Tree','Volcano','Hill','Campsite','Tent',
      'Sleeping Bag','Camp Chair','Picnic Basket','Picnic Table','Fishing Pole','Fishing Net','Life Jacket','Surfboard','Snowboard','Sled','Skis','Ice Skate','Bicycle Helmet','Tire','Wheel','Bumper',
      'Steering Wheel','Seat Belt','Car Key','License Plate','Gas Pump','Traffic Sign','Speed Bump','Parking Meter','Taxi Sign','Train Track','Railroad Crossing','Bus Shelter','Bicycle Rack',
      'Skateboard Ramp','Scooter','Wagon','Wheelchair','Stroller','Shopping Cart','Shopping Bag','Grocery Basket','Vending Machine','ATM','Telephone Booth','Newspaper Stand','Street Sign','Sidewalk',
      'Manhole Cover','Fire Escape','Fountain','Statue','Signpost','Traffic Barricade','Trash Bag','Recycling Bin','Bicycle Bell','Door Handle','Doorknob','Window Blinds','Window Box','Chimney',
      'Roof','Fence Gate','Garden Hose','Sprinkler','Lawn Mower','Birdhouse','Bird Feeder','Mailbox Key','Door Chain','Padlock','Safe','Piggy Bank','Coin','Dollar Bill','Credit Card','Receipt',
      'Shopping List','Ticket','Photograph','Sticker','Bookmark','Sticky Note','Envelope Opener','Pencil Sharpener','Marker','Colored Pencil','Chalk','Eraser Cap','Ruler Case','Scotch Tape',
      'Glue Stick','Rubber Band','Binder Clip','Index Card','Folder','Clipboard','Calculator Buttons','Desk Organizer','Calendar Page','Paint Can','Paint Tube','Paint Sponge','Color Wheel',
      'Sketchbook','Canvas','Easel','Picture','Photo Album','Sticker Sheet','Origami Crane','Paper Airplane','Paper Boat','Paper Clip Chain','String','Yarn','Button','Thread','Needle','Thimble',
      'Scarf Pin','Hairbrush','Hair Tie','Hair Clip','Barrette','Shampoo Bottle','Conditioner Bottle','Lotion Bottle','Perfume Bottle','Deodorant','Razor','Washcloth','Bathrobe','Slippers',
      'Sunglasses','Baseball Cap','Beanie','Sandwich Bag','Backpack Strap','Shoelace','Shoe Box','Raincoat','Winter Coat','Swimsuit','Bathing Cap','Life Preserver','Flippers','Beach Towel',
      'Beach Umbrella','Beach Chair','Bucket Hat','Flip Flops','Knee Pads','Elbow Pads','Knee Brace','Baseball Glove','Baseball Bat','Tennis Ball','Basketball Hoop','Football','Hockey Stick',
      'Hockey Puck','Golf Ball','Golf Club','Golf Flag','Badminton Racket','Shuttlecock','Billiard Ball','Billiard Cue','Dart','Dartboard','Skateboard','Roller Skates','Jump Rope','Exercise Mat',
      'Dumbbell','Trophy','Medal','Whistle Lanyard','Soccer Ball','Basketball','Baseball','Football Helmet','Boxing Glove','Swimming Goggles','Swim Cap','Snorkel','Life Ring','Picnic Blanket',
      'Boarding Pass','Passport','Suitcase Tag','Hotel Key','Room Key','Map Pin','Tourist Camera','Souvenir','Postcard','Travel Pillow','Neck Pillow','Luggage Cart','Airport Sign','Baggage Claim',
      'Escalator','Elevator','Stairs','Crossing Guard','Police Badge','Firefighter Helmet','Doctor Bag','First Aid Kit','Bandage','Crutches','Wheelchair Ramp','Stopwatch','Thermos','Lunch Tray',
      'Plate Rack','Dishwasher','Microwave','Coffee Maker','Can Opener','Bottle Opener','Salt Shaker','Pepper Shaker','Sugar Bowl','Honey Jar','Jam Jar','Ketchup','Mustard','Mayonnaise','Syrup',
      'Spice Rack','Cutting Board','Colander','Measuring Cup','Measuring Spoon','Whisk','Tongs','Oven Mitt','Apron Pocket','Kitchen Timer','Pot Lid','Ice Tray','Food Container','Lunch Bag',
      'Paper Towel','Dish Sponge','Dish Soap','Bottle','Thermos Cup','Straw Hat','Party Balloon','Party Streamer','Party Favor','Gift Bag','Birthday Card','Birthday Cake Slice','Party Whistle',
      'Party Horn','Confetti Popper','Firecracker','Wedding Ring Box','Wedding Cake','Wedding Bouquet','Greeting Card','Thank You Card','Calendar Date','Clock Hands','Alarm Button','Timer',
      'Remote Button','Game Piece','Game Board','Puzzle Box','Dice Cup','Domino Tile','Toy Car','Toy Plane','Toy Boat','Toy Train','Toy Robot','Toy Dinosaur','Toy Castle','Toy Drum','Toy Sword',
      'Toy Bow','Toy Blocks','Building Blocks','Rubiks Cube','Slinky','Jumping Rope','Marionette','Puppet','Pinwheel','Bubble Wand','Bubble','Kaleidoscope','Jack-in-the-Box','Yo-Yo String',
      'Stuffed Bunny','Stuffed Elephant','Toy Doll','Dollhouse','Toy Chest','Action Figure','Superhero Mask','Cape','Crown Jewel','Pirate Hat','Treasure Coin','Treasure Key','Magic Hat','Magic Wand',
      'Wizard Hat','Princess Dress','Knight Helmet','Dragon Egg','Fairy Wings','Monster Mask','Ghost Sheet','Vampire Cape','Witch Hat','Pumpkin Bucket','Scarecrow Hat','Snowman Carrot','Snowman Hat',
      'Snowman Scarf','Snowboard Jump','Waffle Cone','Milkshake','Bubble Bath','Rubber Duck','Shower Head','Toothbrush Holder','Nightlight','Piggy Back Ride','Skateboard Trick','Ice Pop','Gumdrop',
      'Marshmallow','Graham Cracker','Root Beer Float','Snow Cone','Corn on the Cob','Baked Potato','Deviled Egg','Fruit Kabob','Trail Mix Bag','Granola Bar','Cereal Box','Milk Carton','Juice Pouch',
      'Paper Fan','Kazoo','Tambourine','Maracas','Triangle Instrument','Xylophone','Recorder Instrument','Sock Puppet','Finger Puppet','Paper Doll','Cardboard Box','Bubble Mower','Sidewalk Chalk',
      'Water Balloon','Squirt Gun','Slip and Slide','Trampoline','Pogo Stick','Skip Rope','Kickball','Tetherball','Horseshoe','Bean Bag','Cornhole Board','Pinata','Streamers','Party Popper',
      'Ice Pack','Band-Aid','Cotton Ball','Q-Tip','Nail Clipper','Hair Dryer','Curling Iron','Flat Iron','Bath Robe','Slipper','House Key','Car Keys','Wallet Chain','Coin Purse','Cafeteria Table',
      'School Desk','Chalkboard Eraser','Pencil Case','Backpack Zipper','Locker','Hall Pass','Report Card Folder','Yearbook','Graduation Cap','Diploma','Trophy Case',
    ],
    medium: [
      'Fire Station','Police Station','Hospital','Post Office','Grocery Store','Bakery','Barbershop','Hair Salon','Restaurant','Coffee Shop','Movie Theater','Bowling Alley','Train Station',
      'Airport Terminal','Gas Station Attendant','Construction Site','Farmhouse','Barn','Wind Turbine','Solar Panel','Lifeguard','Mail Carrier','Bus Driver','Train Conductor','Pilot',
      'Flight Attendant','Mechanic','Plumber','Electrician','Carpenter','Photographer','Journalist','Artist','Musician','Dancer','Actor','Director','Scientist','Engineer','Architect','Fisherman',
      'Lifeguard Tower','Sailboat Race','Kayaking','Canoeing','Scuba Diving','Snorkeling','Paragliding','Bungee Jumping','Skydiving','Treasure Island','Jungle Temple','Desert Oasis','Mountain Cabin',
      'Forest Ranger Station','Underground Tunnel','Coral Reef','Shipwreck','Glacier','Canyon','Medieval Village','Royal Palace','Egyptian Pyramid','Roman Colosseum','Greek Temple','Japanese Garden',
      'African Safari','Wild West Town','Haunted Carnival','Abandoned Mansion','Monster Truck','Race Car','Fire Truck','Ambulance','Police Car','Garbage Truck','Tow Truck','Bulldozer','Excavator',
      'Crane','Remote-Controlled Car','Model Airplane','Toy Soldier','Jack-in-the-Box','Stuffed Animal','Action Figure','Board Game','Card Trick','Magic Show','Puppet Show','Treasure Vault',
      'Secret Laboratory','Spy Camera','Invisible Cloak','Jetpack','Rocket Fuel','Teleportation Device','Robot Factory','Alien Planet','Space Station','Crystal Cave','Enchanted Garden',
      'Magic Potion Shop','Wizard Tower','Dragon Cave','Giant Footprint','Monster Under the Bed','Cursed Mirror','Talking Statue','Firefighter','Police Officer','Astronaut','Chef','Doctor','Dentist',
      'Magician','Detective','Cowboy','Farmer','Pirate Ship','Viking','Knight','Mermaid','Wizard','Superhero','Ninja','Mummy','Ghost','Werewolf','Giant','Fairy','Genie','Sphinx','Yeti','Unicorn',
      'Griffin','Centaur','Kraken','Sasquatch','Jungle','Desert','Rainforest','Water Park','Amusement Park','Haunted House','Treehouse Village','Iceberg','Waterfall Cave','Volcano Island','Tunnel',
      'Roller Coaster','Ferris Wheel','Zip Line','Hot Air Balloon','Cable Car','Subway','Drawbridge','Lava Field','Observatory','Treasure Hunt','Escape Room','Camping Trip','Road Trip','Sleepover',
      'Birthday Party','Wedding','Parade','Carnival','Concert','Cooking Show','Talent Show','Science Fair','Spelling Bee','Classroom','Library','Museum','Aquarium','Zoo','Theater','Bowling','Golfing',
      'Surfing','Rock Climbing','Horseback Riding','Ice Skating','Skiing','Fishing','Archery','Gymnastics','Martial Arts','Boxing','Baseball Game','Soccer Game','Basketball Game','Tennis Match',
      'Marathon','Relay Race','Obstacle Course','Track Meet','Alien','UFO Landing','Time Machine','Secret Agent','Spy Gadget','Laser Beam','Force Field','Flying Car','Robot Dog','Talking Computer',
      'Magic Carpet','Potion','Crystal Ball','Haunted Forest','Secret Passage','Underground City','Lost Island','Ancient Ruins','Hidden Cave','Cursed Treasure','Elephant','Robot','Volcano','Pirate',
      'Dinosaur','Rainbow','Octopus','Castle','Rocket','Dragon','Campfire','Waterfall','Telescope','Snowboarding','Lighthouse','Kangaroo','Windmill','Treasure Map','Spaceship','Cactus','Beehive',
      'Sandcastle','Tornado','Scarecrow','Fire Escape','Firefighter Training','Firehouse Pole','Police Chase','Police Dog','Detective Office','Emergency Room','Doctors Office','Dental Office',
      'Operating Room','Ambulance Driver','Paramedic','Nurse','Veterinarian','Pharmacy','Dentist Chair','X-Ray Machine','Hospital Bed','Wheelchair Lift','Blood Pressure Test','School Bus',
      'School Principal','Teachers Desk','School Cafeteria','School Locker','Gym Class','Homework','Pop Quiz','Report Card','Graduation','School Play','Field Trip','Book Report','Science Experiment',
      'Art Class','Music Class','Recess','Detention','School Bell','Class Picture','Grocery Shopping','Checkout Counter','Shopping Spree','Store Clerk','Cash Register','Shopping Receipt',
      'Bakery Counter','Pizza Delivery','Food Truck','Ice Cream Truck','Waiter','Waitress','Restaurant Kitchen','Restaurant Menu','Chefs Hat','Cooking Competition','Breakfast in Bed','Burnt Dinner',
      'Kitchen Disaster','Family Dinner','Rock Concert','Drummer','Guitar Solo','Singer on Stage','Backstage Pass','Music Festival','Dance Party','DJ Booth','Karaoke Night','Movie Premiere',
      'Movie Ticket','Movie Popcorn','Film Director','Movie Camera','Red Carpet','Actor Audition','Movie Monster','Comedy Show','Stand-Up Comedian','Magic Trick','Wedding Proposal',
      'Wedding Reception','Bridesmaid','Groomsman','Wedding Invitation','Wedding Photographer','Birthday Surprise','Surprise Party','Family Reunion','Baby Shower','Graduation Party','Costume Party',
      'Sleepover Fight','Housewarming Party','Picnic Date','First Date','Blindfold Game','Musical Chairs','Pin the Tail','Scavenger Hunt','Car Accident','Flat Tire','Car Wash','Car Dealership',
      'Driving Lesson','Parallel Parking','Road Construction','Traffic Jam','Speeding Ticket','Road Trip Stop','Broken-Down Car','Carpool','Motorcycle Helmet','Bicycle Race','Bike Trail',
      'Skateboard Trick','Roller Rink','Go-Kart Racing','Race Track','Pit Stop','Airport Security','Baggage Check','Lost Luggage','Flight Delay','Window Seat','Aisle Seat','Airplane Meal',
      'Pilot Cockpit','Flight Attendant Cart','Airport Lounge','Boarding Gate','Customs Officer','Passport Control','Tourist Attraction','Roadside Motel','Hotel Lobby','Hotel Elevator','Room Service',
      'Hotel Pool','Vacation Resort','Camping Tent','Campfire Cooking','Hiking Trail','Mountain Climber','Hiking Backpack','Trail Marker','Sleeping in a Tent','Fishing Trip','Fishing Boat',
      'Camping Lantern','Campfire Marshmallow','Bear Encounter','Lost Hiker','Nature Photographer','Forest Trail','Waterfall Hike','Cave Explorer','Rock Climber','Mountain Biking','River Rafting',
      'Beach Vacation','Beach Volleyball','Surfing Lesson','Building a Sandcastle','Beach Picnic','Lifeguard Rescue','Snorkeling Trip','Scuba Diver','Underwater Camera','Sailing Trip','Fishing Pier',
      'Boat Dock','Ocean Lighthouse','Tropical Island','Palm Tree Grove','Beach Bonfire','Sunbathing','Beach Cleanup','Crab Walking','Shark Fin','Zoo Keeper','Animal Trainer','Feeding the Animals',
      'Monkey Cage','Penguin Exhibit','Lions Den','Giraffe Feeding','Elephant Ride','Bird Sanctuary','Butterfly Garden','Pet Store','Dog Walker','Dog Park','Cat Cafe','Pet Groomer',
      'Veterinary Clinic','Horse Stable','Horse Race','Cow Milking','Chicken Coop','Garden Party','Planting Flowers','Watering Plants','Pulling Weeds','Gardening Gloves','Greenhouse','Flower Shop',
      'Farmers Market','Apple Orchard','Pumpkin Patch','Corn Maze','Berry Picking','Lemonade Stand','Farm Tractor','Hay Bale','Barnyard','Chicken Farmer','Sheep Shearing','Horse Barn',
      'Scarecrow Contest','Pirate Treasure','Pirate Captain','Pirate Crew','Pirate Flag','Pirate Island','Sailing Ship','Ship Captain','Shipwreck Survivor','Message in a Bottle','Buried Treasure',
      'Treasure Chest Key','Island Explorer','Desert Explorer','Jungle Explorer','Safari Guide','Wild Animal Chase','Rainforest Explorer','Lost Civilization','Ancient Temple','Hidden Waterfall',
      'Medieval Castle','Castle Drawbridge','Castle Dungeon','Royal Banquet','Kings Crown','Queens Throne','Royal Guard','Knight in Armor','Knight Tournament','Dragon Attack','Princess Tower',
      'Wizard School','Witchs Cauldron','Fairy Tale','Magic Spell','Magic Mirror','Enchanted Forest','Flying Broomstick','Giants Castle','Fairy Village','Superhero Landing','Superhero Costume',
      'Superhero Headquarters','Secret Hideout','Villains Lair','Evil Mastermind','Heroic Rescue','Secret Agent Mission','Spy Disguise','Spy Car','Secret Code','Laser Security','Bank Heist',
      'Getaway Car','Police Investigation','Detective Mystery','Mysterious Package','Secret Door','Hidden Treasure','Top Secret File','Alien Abduction','Alien Spaceship','Alien Communication',
      'Space Mission','Space Walk','Moon Landing','Mars Rover','Astronaut Training','Space Helmet','Rocket Launch','Rocket Countdown','Mission Control','Space Station Crew','Meteor Shower',
      'Planet Discovery','Alien Encounter','Flying Saucer','Moon Base','Zero Gravity','Space Telescope','Robot Assistant','Robot Vacuum','Robot Battle','Talking Robot','Computer Hacker',
      'Computer Virus','Video Call','Online Shopping','Social Media Post','Selfie Stick','Virtual Meeting','Video Game Tournament','Gaming Chair','Game Controller','Arcade Machine','Pinball Machine',
      'Dance Game','Virtual Pet','Smart Home','Treasure Hunt Clue','Escape Room Puzzle','Mystery Box','Hidden Door','Secret Tunnel','Locked Room','Riddle Contest','Murder Mystery','Detective Clues',
      'Missing Person','Lost Puppy','Runaway Balloon','Broken Window','Mysterious Footprints','Strange Noise','Hidden Message','Secret Compartment','Map Reading','Following a Trail','Finding a Clue',
      'Roller Coaster Ride','Amusement Park Ticket','Funhouse Mirror','Bumper Cars','Carnival Games','Prize Booth','Ring Toss','Ferris Wheel Ride','Haunted Ride','Water Slide','Wave Pool',
      'Lazy River','Mini Golf','Go-Kart Track','Arcade Prize','Cotton Candy Stand','Carnival Parade','Theme Park Map','Park Mascot','Amusement Park Crowd','Basketball Coach','Basketball Practice',
      'Soccer Referee','Soccer Practice','Baseball Coach','Baseball Practice','Football Referee','Football Practice','Tennis Coach','Golf Caddy','Golf Tournament','Bowling Tournament',
      'Bowling Strike','Ice Hockey Game','Hockey Goalie','Figure Skating','Ski Lift','Snowball Fight','Sledding Race','Gymnastics Competition','Rock Climbing Wall','Obstacle Race','Tug of War',
      'Three-Legged Race','Relay Team','Finish Line','Victory Celebration','Sports Trophy','Team Huddle','Cheerleader','Referee Whistle','Starting Line','Scoreboard','Crowd Cheering',
      'Championship Game','Sports Fan','Tailgate Party','Locker Room','Athlete Stretching','Medal Ceremony','Construction Worker','Construction Helmet','Building Blueprint','Brick Wall','Scaffolding',
      'Cement Mixer','Road Worker','Jackhammer','Tool Belt','Plumber Repair','Electrician Repair','Carpenter Workshop','Painter at Work','Roofer','Moving Day','Moving Truck','Furniture Assembly',
      'Broken Pipe','Leaky Faucet','Power Outage','News Reporter','News Camera','Weather Reporter','Weather Forecast','Newspaper Headline','Radio Host','Podcast Recording','Photographer at Work',
      'Fashion Show','Fashion Model','Art Exhibition','Museum Tour','Historical Exhibit','Science Laboratory','Scientist at Work','Research Project','Invention','Blueprint','Architects Model',
      'Engineering Project','Train Passenger','Subway Passenger','Taxi Driver','Airport Traveler','Tour Guide','Mail Delivery','Package Delivery','Delivery Driver','Garbage Collector',
      'Street Sweeper','Crossing Guard','Construction Inspector','Park Ranger','Forest Guide','Museum Guide','Zoo Guide','Security Guard','Doorman','Detective Hat','Detective Magnifying Glass',
      'Crime Scene','Fingerprint','Footprint Trail','Mysterious Letter','Locked Safe','Disguise','Escape Artist','Prison Escape','Cops and Robbers','Bank Robbery','Stolen Painting','Missing Diamond',
      'Spy Headquarters','Undercover Mission','Hidden Camera','Secret Meeting','Giant Robot','Friendly Monster','Monster Costume','Dragon Rider','Mermaid Lagoon','Unicorn Ride','Giant Spider',
      'Talking Animal','Flying Horse','Invisible Person','Time Traveler','Future City','Flying House','Floating Island','Underwater City','Robot Butler','Alien Pet','Space Pirate','Haunted Hotel',
      'Haunted School','Ghost Hunter','Ghost Story','Monster Movie','Vampire Bite','Werewolf Transformation','Witchs House','Spooky Graveyard','Creepy Doll','Haunted Attic','Mysterious Fog',
      'Scary Mask','Skeleton Dance','Zombie Walk','Haunted Painting','Cursed Object','Haunted Mansion','Midnight','Hammer Time','Brushing Your Teeth','Tying Your Shoes','Riding a Bike',
      'Cooking Dinner','Doing Laundry','Taking a Selfie','Sneezing','Yawning','Shivering','Laughing Hysterically','Crying','Milking a Cow','Shoveling Snow','Raking Leaves','Painting a Fence',
      'Changing a Tire','Flipping a Pancake','Blowing Out Candles','Popping a Balloon','Walking a Tightrope','Doing a Cartwheel','Juggling','Skipping Stones','Flying a Kite','Chopping Wood',
      'Digging a Hole','Climbing a Ladder','Hammering a Nail','Vacuuming','Ironing Clothes','Folding Laundry','Setting the Table','Washing Dishes','Mowing the Lawn','Rocking a Baby to Sleep',
      'Giving a Piggyback Ride','Tip-Toeing','Sleepwalking','Snoring','Stretching','Doing Push-Ups','Lifting Weights','Running a Marathon','Shooting a Basketball','Swinging a Golf Club',
      'Swinging a Baseball Bat','Serving a Tennis Ball','Kicking a Soccer Ball','Diving into a Pool','Blowing a Bubble with Gum','Tightrope Walking','Balancing on One Foot','Doing the Robot Dance',
      'Moonwalking','Break Dancing','Playing an Air Guitar','Conducting an Orchestra','Rowing a Boat','Paddling a Canoe','Casting a Fishing Line','Reeling in a Fish','Shearing a Sheep',
      'Churning Butter','Kneading Dough','Rolling Out Dough','Frosting a Cake','Piping Icing','Carving a Pumpkin','Wrapping a Present','Blowing Up a Balloon','Lighting a Candle','Putting Out a Fire',
      'Climbing a Tree','Skipping Rope','Bouncing a Ball','Catching a Frisbee','Throwing a Football','Spiking a Volleyball','Doing a Handstand','Doing a Somersault','Tiptoeing Past Someone Asleep',
      'Eavesdropping','Whispering a Secret','Holding Your Breath Underwater','Blowing Out a Match','Fanning Yourself','Wiping Sweat Off Your Brow','Shrugging Your Shoulders','Rolling Your Eyes',
      'Facepalming','Crossing Your Fingers','Knocking on Wood','Zipping Your Lips','Biting Your Nails','Twiddling Your Thumbs','Pacing Back and Forth','Tapping Your Foot Impatiently',
      'Checking Your Watch','Counting on Your Fingers','Raising Your Hand','Giving a Thumbs Up','Giving a High Five','Fist Bumping','Taking a Bow','Curtsying',
    ],
    hard: [
      'Imposter Syndrome','Fear of Missing Out','Writers Block','Creative Burnout','Confirmation Bias','Peer Pressure','Groupthink','Stage Fright','Culture Shock','Identity Crisis',
      'Existential Crisis','Midlife Crisis','Generation Gap','Communication Barrier','Language Barrier','Trust Issues','Broken Promise','Secret Admirer','Unrequited Love','Mixed Signals',
      'Awkward Silence','First Impressions','Personal Space','Social Norms','Double Standard','Moral Dilemma','Conflict of Interest','Hidden Motive','Ulterior Motive','Unexpected Consequences',
      'Unintended Consequences','Trial by Fire','Leap of Faith','Act of Rebellion','Fresh Start','Clean Slate','Turning Point','Point of No Return','Crossroads','Needle in a Haystack',
      'Wolf in Sheeps Clothing','Fish Out of Water','Skeleton in the Closet','Dark Horse','Loose Cannon','Bigger Picture','Common Ground','Grey Area','Fine Line','Red Tape','Wild Goose Chase',
      'Can of Worms','Pandoras Box','Trojan Horse','House of Cards','A Storm in a Teacup','The Tip of the Iceberg','Through Thick and Thin','Cause and Consequence','Action and Reaction',
      'Order and Chaos','Beginning and End','Past and Future','Life Cycle','Circle of Life','Balance of Power','Power Struggle','Energy Transfer','Gravitational Pull','Electric Current',
      'Chemical Reaction','Evaporation','Condensation','Water Cycle','Carbon Cycle','Nitrogen Cycle','Rock Cycle','Evolutionary Adaptation','Natural Disaster','Invasive Species','Endangered Species',
      'Solar Flare','Supernova','Neutron Star','Asteroid Belt','Light-Year','Archaeological Artifact','Ancient Manuscript','Hieroglyphics','Rosetta Stone','Lost Treasure','Secret Society',
      'Historical Mystery','Time Capsule','Time Loop','Parallel Universe','Alternate Reality','False Memory','Daydreaming','Overthinking','Homesickness','Jet Lag','Road Rage','Social Anxiety',
      'Curiosity','Jealousy','Nostalgia','Determination','Imagination','Creativity','Confusion','Distraction','Suspicion','Embarrassment','Confidence','Loneliness','Friendship','Betrayal',
      'First Impression','Second Chance','Breaking a Habit','Making a Decision','Changing Your Mind','Keeping a Secret','Reading Between the Lines','Mixed Feelings','Lost for Words','Inside Joke',
      'Guilty Conscience','Cause and Effect','Trial and Error','Risk and Reward','Supply and Demand','Chain Reaction','Domino Effect','Butterfly Effect','Ripple Effect','Snowball Effect','Catch-22',
      'Murphys Law','Act of Kindness','Blind Date','Cold Shoulder','Red Herring','Elephant in the Room','Under the Weather','Break the Ice','Walking on Eggshells','Bite the Bullet',
      'Hit the Nail on the Head','Once in a Blue Moon','Spill the Beans','Let the Cat Out of the Bag','Cost an Arm and a Leg','Back to Square One','The Last Straw','Jumping to Conclusions',
      'Barking Up the Wrong Tree','Miss the Boat','Digital Footprint','Virtual Reality','Artificial Intelligence','Machine Learning','Cybersecurity','Black Hole','Dark Matter','Parallel Lines',
      'Probability','Infinity','Magnetic Field','Sound Wave','Friction','Photosynthesis','Food Chain','Natural Selection','Genetic Mutation','Carbon Footprint','Climate Change','Ocean Current',
      'Tectonic Shift','Ecosystem','Earthquake Aftershock','Tsunami Warning','Dust Storm','Thunderstorm','Heat Wave','Polar Vortex','Flash Flood','Landslide','Drought','Wildfire','Archaeological Dig',
      'Ancient Civilization','Medieval Tournament','Industrial Revolution','Space Exploration','Alien Invasion','Robot Uprising','Secret Identity','Time Travel','Optical Illusion','Gravity',
      'Nightmare','Procrastination','Claustrophobia','Camouflage','Reflection','Silhouette','Echo','Constellation','Hibernation','Migration','Symmetry','Eclipse','Avalanche','Quicksand',
      'Metamorphosis','Hypnosis','Turbulence','Stalactite','Boomerang','Whirlpool','Mirage','Deja Vu','False Alarm','False Hope','False Start','False Pretenses','Broken Heart','Broken Record',
      'Broken Glass','Broken Clock','Broken Chain','Broken Dreams','Broken Trust','Broken Friendship','Broken Routine','Broken Rule','Broken Habit','Broken Compass','Broken Engagement',
      'Hidden Agenda','Hidden Talent','Hidden Treasure Room','Hidden Doorway','Hidden Passage','Hidden Camera','Hidden Meaning','Hidden Evidence','Hidden Danger','Hidden Message','Hidden Identity',
      'Hidden Ingredient','Hidden Treasure Map','Hidden Room','Hidden Witness','Hidden Camera Footage','Secret Ingredient','Secret Handshake','Secret Meeting','Secret Password','Secret Code',
      'Secret Hideout','Secret Passage','Secret Diary','Secret Weapon','Secret Recipe','Secret Plan','Secret Mission','Secret Door','Secret Tunnel','Secret Garden','Secret Compartment','Secret Club',
      'Secret Letter','Secret Witness','Mind Games','Mind Reading','Mind Control','Mind Over Matter','State of Mind','Change of Heart','Change of Plans','Change of Pace','Change of Scenery',
      'Change of Direction','Change of Subject','Change of Fortune','Change of Perspective','Meeting of the Minds','Peace of Mind','Food for Thought','Lost in Thought','Deep in Thought',
      'Second Thoughts','Third Wheel','Eleventh Hour','Last-Minute Decision','Fresh Perspective','Clean Break','Clean Sweep','Blank Slate','New Beginning','New Perspective','Breaking Point',
      'Breaking News','Breaking the Rules','Breaking the Silence','Breaking the Habit','Crossing the Line','Drawing the Line','Moving the Goalposts','Bait and Switch','Give and Take','Push and Pull',
      'Trial Run','Practice Makes Perfect','Learn the Hard Way','Backseat Driver','Playing Devils Advocate','Playing With Fire','Playing It Safe','Playing Both Sides','Calling the Shots',
      'Calling Someones Bluff','Reading the Room','Reading the Situation','Missing the Point','Getting the Point','Making a Point','Point of View','Point of Contact','On the Same Page',
      'Out of the Loop','Out of Control','Out of Character','Out of Order','Out of Bounds','Out of Reach','Out of Sight','Out of Practice','Out of Time','In the Long Run','In the Nick of Time',
      'In Over Your Head','In Hot Water','In the Spotlight','In Plain Sight','In Deep Trouble','In the Same Boat','In the Dark','In a Tight Spot','Between a Rock and a Hard Place','Between the Lines',
      'Between Two Worlds','Caught in the Middle','Caught Red-Handed','Caught Off Guard','Caught in the Act','Caught in a Trap','Caught Between Friends','Caught in Traffic','Caught in the Rain',
      'Caught by Surprise','Caught on Camera','Caught in a Lie','Caught in the Crossfire','Against the Clock','Against All Odds','Against the Grain','Against the Rules','Against the Wind',
      'Against the Current','Under Pressure','Under Arrest','Under Construction','Under Investigation','Undercover Operation','Under Surveillance','Under Attack','Under Suspicion',
      'Underwater Exploration','Under Lock and Key','Under New Management','Under a Spell','Walking on Thin Ice','Walking a Fine Line','Walking in Someones Shoes','Walking Into a Trap',
      'Walking Against the Wind','Walking in Circles','Walking the Plank','Running Out of Time','Running on Empty','Running in Place','Running for Office','Running the Show','Running the Numbers',
      'Running Away From Home','Running Into Trouble','Running With the Bulls','Jumping the Gun','Jumping to a Conclusion','Jumping Through Hoops','Jumping for Joy','Jumping Ship','Jumping the Fence',
      'Jumping Off the Deep End','Falling Behind','Falling Apart','Falling for a Trick','Falling Into a Trap','Falling From Grace','Falling Head Over Heels','Falling Through the Cracks',
      'Falling on Deaf Ears','Turning a Blind Eye','Turning Over a New Leaf','Turning the Tables','Turning Back Time','Turning Up the Heat','Turning Down an Offer','Turning Someone Away',
      'Turning a Corner','Turning the Tide','Keeping Up Appearances','Keeping Your Cool','Keeping Someone Guessing','Keeping an Open Mind','Keeping a Low Profile','Keeping Score','Keeping the Peace',
      'Keeping Your Distance','Keeping Something Under Wraps','Keeping Your Fingers Crossed','Breaking Someones Heart','Breaking the News','Breaking Rank','Breaking Ground','Breaking Even',
      'Breaking a Record','Breaking Character','Breaking Formation','Breaking Free','Breaking Into a House','Making Ends Meet','Making a Scene','Making Waves','Making a Comeback','Making a Splash',
      'Making an Entrance','Making a Fortune','Making a Fool of Yourself','Making a Mountain Out of a Molehill','Making Up Your Mind','Losing Your Head','Losing Your Temper','Losing Track of Time',
      'Losing Your Balance','Losing Your Patience','Losing Your Way','Losing Your Grip','Losing Face','Losing Touch','Losing Interest','Biting Off More Than You Can Chew','Biting Your Tongue',
      'Biting the Hand That Feeds You','Biting Your Nails','Holding Your Breath','Holding a Grudge','Holding the Line','Holding Your Ground','Holding Back Tears','Holding All the Cards',
      'Pulling Someones Leg','Pulling Strings','Pulling Your Weight','Pulling Out All the Stops','Pulling the Plug','Pulling Rank','Pulling a Fast One','Pulling Yourself Together','Pushing Your Luck',
      'Pushing the Limits','Throwing in the Towel','Throwing Someone Under the Bus','Throwing a Curveball','Throwing Caution to the Wind','Throwing a Tantrum','Throwing a Fit',
      'Throwing Your Weight Around','Throwing a Surprise Party','Throwing Someone Off','Throwing the Book at Someone','Breaking the Fourth Wall','Escaping a Maze','Solving a Murder Mystery',
      'Disarming a Trap','Defusing a Bomb','Escaping From Prison','Sneaking Past a Guard','Breaking Into a Vault','Stealing a Priceless Painting','Cracking a Secret Code','Finding a Hidden Passage',
      'Changing the Past','Changing the Future','Repeating the Same Day','Preventing a Disaster','Stopping a Meteor','Saving the World','Destroying the World','Living on Another Planet',
      'Living Underwater','Living in a Floating City','Invisible Wall','Invisible Friend','Invisible Enemy','Invisible Barrier','Invisible Ink','Invisible Hand','Invisible Force','Invisible Door',
      'Invisible Bridge','Invisible Man','Mirror Image','Mirror Maze','Mirror Reflection','Broken Reflection','Endless Hallway','Endless Staircase','Infinite Corridor','Never-Ending Story',
      'Never-Ending Road','Bottomless Pit','Bottomless Cup','Endless Ocean','Optical Trick','Visual Illusion','Double Vision','Disappearing Object','Vanishing Point','Shifting Shape',
      'Impossible Object','Impossible Staircase','Upside-Down World','Backwards Clock','Floating Object','Levitation','Teleportation','Shape-Shifting','Time Freeze','Collective Memory',
      'Subconscious Mind','Inner Voice','Inner Conflict','Inner Peace','Emotional Roller Coaster','Emotional Baggage','Emotional Support','Emotional Breakdown','Nervous Breakdown','Identity Theft',
      'Identity Swap','Personality Change','Memory Loss','Memory Palace','Memory Lane','Lost Memory','Forgotten Password','Forgotten Birthday','Fear of Heights','Fear of the Dark','Fear of Failure',
      'Fear of Success','Fear of Change','Fear of Public Speaking','Fear of Spiders','Fear of Commitment','Fear of the Unknown','Fear of Rejection','Paranoia','Panic Attack','Nervous Energy',
      'Awkward Moment','Awkward Encounter','Uncomfortable Question','Uncomfortable Truth','Hard Truth','Home Alone','Feeling Left Out','Envy','Regret','Remorse','Guilt','Shame','Pride','Hope',
      'Despair','Relief','Frustration','Anticipation','Admiration','Disappointment','Temptation','Indecision','Impatience','Surprise','Chain of Events','Domino Chain','Infinite Loop','Heat Transfer',
      'Sound Barrier','Speed of Light','Zero Gravity','Magnetic Attraction','Magnetic Repulsion','Static Electricity','Electric Shock','Chemical Bond','DNA Strand','Genetic Engineering',
      'Cell Division','Stem Cell','Microscopic Organism','Food Web','Predator and Prey','Survival of the Fittest','Natural Habitat','Animal Migration','Pollination','Decomposition','Bioluminescence',
      'Greenhouse Effect','Ozone Layer','Melting Ice Caps','Rising Sea Levels','Ocean Pollution','Plastic Island','Coral Bleaching','Deforestation','Forest Fire Smoke','Air Pollution',
      'Water Pollution','Acid Rain','Erosion','Sinkhole','Mudslide','Dust Devil','Lightning Strike','Hailstorm','Blizzard','Monsoon','Lunar Eclipse','Solar Eclipse','Shooting Comet',
      'Expanding Universe','Galaxy Collision','Dying Star','Star Formation','Planetary Rings','Meteor Impact','Asteroid Collision','Space Debris','Wormhole','Alien Civilization',
      'Extraterrestrial Life','Interstellar Travel','Lost City','Ancient Ruins','Forbidden Temple','Secret Chamber','Ancient Treasure','Historical Artifact','Ancient Map','Ancient Prophecy',
      'Unsolved Mystery','Ancient Curse','Revolution','Political Scandal','Peace Treaty','Trade War','Power Vacuum','Border Dispute','Invention of the Wheel','First Contact','Fall of a Kingdom',
      'Clone','Augmented Reality','Deepfake','Facial Recognition','Voice Recognition','Self-Driving Car','Autonomous Drone','Virtual Assistant','Social Experiment','Psychological Experiment',
      'Mob Mentality','Social Butterfly','Outsider','Generational Talent','Lost in Translation','Misunderstanding','Breakdown','Foregone Conclusion','Silent Treatment','Rumor Mill','Gossip',
      'Trust Fall','Compromise','Detour','Plot Twist','Narrator','Redemption Arc','A Heros Welcome','Fall From Glory','Rise to Power','Underdog','Wild Card','Loose End','Missing Link','Missing Piece',
      'Piece of the Puzzle','Bigger Fish to Fry','Drop in the Bucket','Tip of the Tongue','Happy Go Lucky','Ace in the Hole','Jack of All Trades','Master of None','Dark Secret','Open Secret',
      'Best-Kept Secret','Hurt Feelings','Spilling the Tea','Paper Tiger','Burning Bridges','Crossing Bridges','Building Bridges','Bridging the Gap','Closing the Gap',
      'Cross that Bridge When we Get to it','Widening the Gap','Breaking the Sound Barrier','Hitting a Roadblock','Dead End','Deadlock','Stalemate','Standstill','Turning Back','Going in Circles',
      'Taking the Long Way','Wrong Turn','Finding Your Way','Going down the Wrong Path','Once in a Lifetime','Once Upon a Time','A Matter of Time','Race Against Time','Time on Your Hands',
      'Time Flies','Time Is Money','Killing Time','Wasting Time','Buying Time','Borrowed Time','Frozen in Time','Time Stands Still','A Sign of the Times','Ahead of Your Time','The Passage of Time',
      'Test of Time','Changing With the Times','Time Is Running Out','Beat Around the Bush','Add Fuel to the Fire','Every Dog Has Its Day','The Ball Is in Your Court','Burn the Midnight Oil',
      'Cut Corners','Cry Wolf','Get Your Foot in the Door','Go the Extra Mile','Hit the Sack','Its Raining Cats and Dogs','Jump on the Bandwagon','Kill Two Birds with One Stone',
      'Let Sleeping Dogs Lie','Piece of Cake','Put All Your Eggs in One Basket','See Eye to Eye','Speak of the Devil','Steal Someones Thunder','Take It with a Grain of Salt','Under the Radar',
      'Up in the Air','When It Rains It Pours','Your Guess Is as Good as Mine','A Blessing in Disguise','A Penny for Your Thoughts','Back to the Drawing Board','Beat a Dead Horse',
      'Bend Over Backwards','Best Thing Since Sliced Bread','Bite the Dust','Bury the Hatchet','By the Skin of Your Teeth','Call It a Day','Chip on Your Shoulder','Costs a Pretty Penny',
      'Down to the Wire','Draw a Blank','An Elephant Never Forgets','Face the Music','Feeling Blue','Fit as a Fiddle','Fly by the Seat of Your Pants','Get a Second Wind','Get Cold Feet',
      'Give the Benefit of the Doubt','Go Cold Turkey','Go Down in Flames','Head in the Clouds','Hit the Books','Hit the Hay','It Takes Two to Tango','Jump the Shark','Keep Your Chin Up',
      'Knock on Wood','Let the Chips Fall Where They May','Life in the Fast Lane','Living Paycheck to Paycheck','Method to the Madness','Off the Beaten Path','On Cloud Nine','On the Fence',
      'Out on a Limb','Over the Moon','Pass with Flying Colors','Pull the Wool Over Someones Eyes','Put Your Best Foot Forward','Raining on Someones Parade','Read the Fine Print','Rock the Boat',
      'Rule of Thumb','Sixth Sense','Sleep on It','Steal the Show','Straight from the Horses Mouth','Sweat It Out','Take a Rain Check','The Grass Is Always Greener','The Writing Is on the Wall',
      'Tie the Knot','Time Will Tell','Turn a New Page','Under Your Belt','Up to Your Ears','Weather the Storm','You Cant Have Your Cake and Eat It Too','A Taste of Your Own Medicine',
      'Actions Speak Louder','Better Safe Than Sorry','Dont Count Your Chickens','Dont Cry Over Spilled Milk','Every Cloud Has a Silver Lining','Like Father Like Son','No Pain No Gain',
      'Out of Sight Out of Mind','The Early Bird Gets the Worm','Two Wrongs Dont Make a Right','When in Rome','Where Theres a Will Theres a Way','A Dime a Dozen','A Fish Out of Water',
      'A Piece of Work','All Bark and No Bite','All Ears','An Uphill Battle','Bad Blood','Beating Yourself Up','Beyond a Shadow of a Doubt','Bird\'s-Eye View','Bite Sized','Blow Off Steam',
      'Break a Leg','Bring Home the Bacon','Calm Before the Storm','Cat Got Your Tongue','Coast Is Clear','Cool as a Cucumber','Curiosity Killed the Cat','Cutting It Close','Dog Eat Dog',
      'Down in the Dumps','Drastic Times Call for Drastic Measures','Drive Someone Up the Wall','Easier Said Than Done','Fair and Square','Fall Off the Wagon','Feeling Under the Weather',
      'Fish for Compliments','Full Circle','Get the Ball Rolling','Give It a Shot','Go Above and Beyond','Go Out on a Limb','Going Through the Motions','Great Minds Think Alike',
      'Have a Change of Heart','In a Nutshell','In the Heat of the Moment','It\'s Not Rocket Science','Judge a Book by Its Cover','Keep Your Eyes Peeled','Kick the Bucket','Last Laugh',
      'Live and Learn','Look Before You Leap','Making a Mountain','No Strings Attached','On Thin Ice','Out of the Blue','Play It by Ear','Rain or Shine','Sit Tight','Small Talk','Speak Your Mind',
      'Sugarcoat It','Take the Plunge','Talk Is Cheap','The Ball\'s in Your Court','The Last Word','Tip of the Iceberg','Two Peas in a Pod','Under Someone\'s Skin','Whole Nine Yards','Word of Mouth',
      'Wrap Your Head Around It',
    ],
  }
